# Generated by Django 5.2.6 on 2025-09-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coingecko_id', models.CharField(max_length=128, unique=True)),
                ('symbol', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('market_cap_rank', models.IntegerField(null=True)),
                ('last_price', models.DecimalField(decimal_places=10, max_digits=30)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=30)),
                ('percent_change_24h', models.FloatField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
