# Generated by Django 5.2.6 on 2025-09-26 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=10, max_digits=30)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='apis.coin')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('coin', 'date')},
            },
        ),
    ]
